name: wp3-solutions 

on:
  push:
    branches:
      - master

jobs:

  # Build and test the applications with multiple Java versions
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
#          '9.0.x',
#          '11.0.x',
#          '12.0.x',
#          '13.0.x',
#          '14.0.x',
#          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'

      - name: Build for Eclipse
        run: |
          ./config.sh

      - name: Run Californium & ACE JUnit tests
        run: |
          ./test-californium.sh
          ./test-ace.sh --with-mysql
          ./code-coverage.sh

      - name: Deploy Jacoco code coverage reports to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ matrix.java-version == '8.0.x' }}
        with:
          clean: true
          folder: jacoco
          target-folder: reports
          branch: gh-pages

  
  # Build files neccessary for building of Docker Images
  build-for-docker:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8.0.x
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'
          
      - name: Prepare Dockerfiles and files for Contexts
        run: |
          ./build-for-docker.sh
             
      - name: Upload artifacts for Docker Image building
        uses: actions/upload-artifact@v3
        with:
          name: files-for-docker
          retention-days: 5
          if-no-files-found: error
          path: |
            ./*/group/*
            ./*/edhoc/*
            ./*/group/lib/*
            ./*/edhoc/lib/*
  

  # Build multiarch Docker Images and push as Github Packages
  docker:

    if: ${{ github.repository == 'Daven00/sifis-home-wp3' }}
    needs: [build-and-test, build-for-docker]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts for Docker Image building
        uses: actions/download-artifact@v3
        with:
          name: files-for-docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (Group Manager)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreRsServer
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/Daven00/group-manager:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group Manager (ACE Resource Server)
          labels: |
            app_label=TheAppLabel
            code_coverage=CodeCoverageResults2

      - name: Build and push image (EDHOC Phase4Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase4Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/Daven00/phase4-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase4Client (EDHOC client using method 3 and the optimized request)

